apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS mensagens (
      id INT NOT NULL,
      nome VARCHAR(100) NOT NULL,
      email VARCHAR(150) NOT NULL,
      comentario VARCHAR(300) NOT NULL,
      PRIMARY KEY (id)
    );
