apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: LoadBalancer
  loadBalancerIP: SHARED_STATIC_IP
  selector:
    app: backend
  ports:
    - port: 30080
      targetPort: 80
