apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: SHARED_STATIC_IP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
